{
 "title": "Main",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "API instance count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_running{task_group=\"api\"}"
    }
   ]
  },
  {
   "title": "API requests duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=~\"/api.*\"}[5m]) / rate(http_server_requests_seconds_count{uri=~\"/api.*\"}[5m])",
     "legendFormat": "{{instance}} - {{uri}}"
    }
   ]
  },
  {
   "title": "API requests count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (uri) (http_server_requests_seconds_count{uri=~\"/api/.*\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "API CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(process_cpu_usage)", "legendFormat": "Process CPU Usage" },
    { "expr": "sum(system_cpu_usage)", "legendFormat": "System CPU Usage" }
   ]
  },
  {
   "title": "API Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Nomad Job Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nomad_nomad_job_status_running", "legendFormat": "Running Jobs" },
    { "expr": "nomad_nomad_job_status_dead", "legendFormat": "Dead Jobs" },
    { "expr": "nomad_nomad_job_status_pending", "legendFormat": "Pending Jobs" }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_client_host_memory_total)",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(nomad_client_host_memory_used)",
     "legendFormat": "Memory Used"
    }
   ]
  },
  { "type": "welcome", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 32 } },
  { "type": "gettingstarted", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 } },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 15, "w": 12, "x": 0, "y": 44 } },
  { "title": "Latest from the blog", "type": "news", "gridPos": { "h": 15, "w": 12, "x": 12, "y": 44 } }
 ]
}